import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "prod_001",
    name: "Oversized Wide-Leg Pants",
    slug: "oversized-wide-leg-pants",
    description:
      "Designed for effortless movement and modern silhouette, these wide-leg pants are cut in a relaxed, oversized fit that drapes beautifully. Crafted from a lightweight fabric blend with subtle structure, they transition seamlessly from desk to dinner. The high-rise waist elongates the figure while the wide leg creates a balanced, editorial proportion.",
    shortDescription: "Relaxed wide-leg cut with a high-rise waist. The effortless trouser.",
    price: 68,
    compareAtPrice: 95,
    supplierCost: 18.5,
    shippingCost: 6.5,
    estimatedMargin: 43,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4b4f53?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1620799139834-6b8f844fbe61?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80",
    ],
    colors: [
      { name: "Ivory", hex: "#F5F0E8" },
      { name: "Slate", hex: "#6B7280" },
      { name: "Espresso", hex: "#3C2A1E" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "72% Viscose, 25% Polyester, 3% Elastane",
    fit: "Oversized, relaxed fit. Model is 5'9\" wearing size S. We recommend sizing down for a more fitted silhouette.",
    careInstructions: [
      "Hand wash cold or gentle machine wash",
      "Do not bleach",
      "Low iron if needed",
      "Do not tumble dry — lay flat to dry",
    ],
    shippingInfo: "Free shipping on orders over $75. Standard delivery 7–14 business days.",
    returnInfo: "Free returns within 30 days of delivery. Items must be unworn, unwashed, and with original tags.",
    cjProductId: "CJ_WIDE_LEG_001",
    variants: [
      { id: "v001a", color: "Ivory", colorHex: "#F5F0E8", size: "XS", sku: "WLP-IVR-XS", stock: 15, cjVariantId: "CJV_WLP_IVR_XS" },
      { id: "v001b", color: "Ivory", colorHex: "#F5F0E8", size: "S", sku: "WLP-IVR-S", stock: 20, cjVariantId: "CJV_WLP_IVR_S" },
      { id: "v001c", color: "Ivory", colorHex: "#F5F0E8", size: "M", sku: "WLP-IVR-M", stock: 18, cjVariantId: "CJV_WLP_IVR_M" },
      { id: "v001d", color: "Ivory", colorHex: "#F5F0E8", size: "L", sku: "WLP-IVR-L", stock: 12, cjVariantId: "CJV_WLP_IVR_L" },
      { id: "v001e", color: "Ivory", colorHex: "#F5F0E8", size: "XL", sku: "WLP-IVR-XL", stock: 8, cjVariantId: "CJV_WLP_IVR_XL" },
      { id: "v001f", color: "Slate", colorHex: "#6B7280", size: "XS", sku: "WLP-SLT-XS", stock: 10, cjVariantId: "CJV_WLP_SLT_XS" },
      { id: "v001g", color: "Slate", colorHex: "#6B7280", size: "S", sku: "WLP-SLT-S", stock: 15, cjVariantId: "CJV_WLP_SLT_S" },
      { id: "v001h", color: "Slate", colorHex: "#6B7280", size: "M", sku: "WLP-SLT-M", stock: 14, cjVariantId: "CJV_WLP_SLT_M" },
      { id: "v001i", color: "Espresso", colorHex: "#3C2A1E", size: "S", sku: "WLP-ESP-S", stock: 9, cjVariantId: "CJV_WLP_ESP_S" },
      { id: "v001j", color: "Espresso", colorHex: "#3C2A1E", size: "M", sku: "WLP-ESP-M", stock: 11, cjVariantId: "CJV_WLP_ESP_M" },
    ],
    status: "Active",
    category: "Bottoms",
    tags: ["wide-leg", "trousers", "relaxed", "bestseller"],
    rating: 4.7,
    reviewCount: 142,
    featured: true,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "prod_002",
    name: "Structured Corset Mini Dress",
    slug: "structured-corset-mini-dress",
    description:
      "A statement piece that commands attention. Our corset mini dress features boning detail and a structured bodice that defines the waist while the mini hem adds a modern edge. The back lace-up closure allows for a customized fit. Available in our signature palette — wear alone or layer with an oversized blazer for an elevated ensemble.",
    shortDescription: "Boned bodice, lace-up back, figure-defining silhouette.",
    price: 89,
    compareAtPrice: 120,
    supplierCost: 24,
    shippingCost: 7,
    estimatedMargin: 58,
    images: [
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1566206091558-7f218b696731?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80",
    ],
    colors: [
      { name: "Onyx", hex: "#1A1A1A" },
      { name: "Champagne", hex: "#E8D5B0" },
      { name: "Bordeaux", hex: "#5C1A2A" },
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "65% Cotton, 30% Polyester, 5% Spandex with boning inserts",
    fit: "True to size with structured boning. Lace-up back offers adjustability. Model is 5'8\" wearing size S.",
    careInstructions: [
      "Hand wash cold only",
      "Do not bleach",
      "Do not tumble dry",
      "Hang or lay flat to dry",
      "Cool iron on reverse",
    ],
    shippingInfo: "Free shipping on orders over $75. Standard delivery 7–14 business days.",
    returnInfo: "Free returns within 30 days of delivery. Items must be unworn, unwashed, and with original tags.",
    cjProductId: "CJ_CORSET_002",
    variants: [
      { id: "v002a", color: "Onyx", colorHex: "#1A1A1A", size: "XS", sku: "CMD-ONX-XS", stock: 12, cjVariantId: "CJV_CMD_ONX_XS" },
      { id: "v002b", color: "Onyx", colorHex: "#1A1A1A", size: "S", sku: "CMD-ONX-S", stock: 18, cjVariantId: "CJV_CMD_ONX_S" },
      { id: "v002c", color: "Onyx", colorHex: "#1A1A1A", size: "M", sku: "CMD-ONX-M", stock: 16, cjVariantId: "CJV_CMD_ONX_M" },
      { id: "v002d", color: "Onyx", colorHex: "#1A1A1A", size: "L", sku: "CMD-ONX-L", stock: 10, cjVariantId: "CJV_CMD_ONX_L" },
      { id: "v002e", color: "Champagne", colorHex: "#E8D5B0", size: "XS", sku: "CMD-CHP-XS", stock: 8, cjVariantId: "CJV_CMD_CHP_XS" },
      { id: "v002f", color: "Champagne", colorHex: "#E8D5B0", size: "S", sku: "CMD-CHP-S", stock: 14, cjVariantId: "CJV_CMD_CHP_S" },
      { id: "v002g", color: "Champagne", colorHex: "#E8D5B0", size: "M", sku: "CMD-CHP-M", stock: 12, cjVariantId: "CJV_CMD_CHP_M" },
      { id: "v002h", color: "Bordeaux", colorHex: "#5C1A2A", size: "S", sku: "CMD-BRD-S", stock: 6, cjVariantId: "CJV_CMD_BRD_S" },
      { id: "v002i", color: "Bordeaux", colorHex: "#5C1A2A", size: "M", sku: "CMD-BRD-M", stock: 8, cjVariantId: "CJV_CMD_BRD_M" },
    ],
    status: "Winner",
    category: "Dresses",
    tags: ["corset", "mini", "dress", "bestseller", "featured"],
    rating: 4.9,
    reviewCount: 287,
    featured: true,
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "prod_003",
    name: "Oversized Linen-Look Shirt",
    slug: "oversized-linen-look-shirt",
    description:
      "The shirt that goes everywhere. Cut in an oversized, relaxed silhouette from our linen-look fabric — breathable, lived-in, and effortlessly cool. Wear fully buttoned as a blouse, half-tucked into trousers, or open over a fitted dress. The drop shoulder and relaxed hem make this one of those pieces you'll reach for every day.",
    shortDescription: "Breathable linen-look fabric, drop shoulder, wear it every way.",
    price: 52,
    compareAtPrice: undefined,
    supplierCost: 14,
    shippingCost: 5.5,
    estimatedMargin: 32.5,
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1554412933-514a83d2f3c8?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&auto=format&fit=crop&q=80",
    ],
    colors: [
      { name: "Natural", hex: "#E8E0D0" },
      { name: "Sage", hex: "#8A9E80" },
      { name: "White", hex: "#F8F8F6" },
      { name: "Black", hex: "#1A1A1A" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "55% Linen, 45% Viscose — linen-look blend",
    fit: "Oversized. If between sizes, size down for a relaxed fit, size up for an extra roomy feel. Model is 5'7\" wearing size XS.",
    careInstructions: [
      "Machine wash cold on gentle cycle",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    shippingInfo: "Free shipping on orders over $75. Standard delivery 7–14 business days.",
    returnInfo: "Free returns within 30 days of delivery. Items must be unworn, unwashed, and with original tags.",
    cjProductId: "CJ_LINEN_003",
    variants: [
      { id: "v003a", color: "Natural", colorHex: "#E8E0D0", size: "XS", sku: "LBS-NAT-XS", stock: 20, cjVariantId: "CJV_LBS_NAT_XS" },
      { id: "v003b", color: "Natural", colorHex: "#E8E0D0", size: "S", sku: "LBS-NAT-S", stock: 25, cjVariantId: "CJV_LBS_NAT_S" },
      { id: "v003c", color: "Natural", colorHex: "#E8E0D0", size: "M", sku: "LBS-NAT-M", stock: 22, cjVariantId: "CJV_LBS_NAT_M" },
      { id: "v003d", color: "Natural", colorHex: "#E8E0D0", size: "L", sku: "LBS-NAT-L", stock: 15, cjVariantId: "CJV_LBS_NAT_L" },
      { id: "v003e", color: "Sage", colorHex: "#8A9E80", size: "S", sku: "LBS-SAG-S", stock: 18, cjVariantId: "CJV_LBS_SAG_S" },
      { id: "v003f", color: "Sage", colorHex: "#8A9E80", size: "M", sku: "LBS-SAG-M", stock: 16, cjVariantId: "CJV_LBS_SAG_M" },
      { id: "v003g", color: "White", colorHex: "#F8F8F6", size: "XS", sku: "LBS-WHT-XS", stock: 14, cjVariantId: "CJV_LBS_WHT_XS" },
      { id: "v003h", color: "White", colorHex: "#F8F8F6", size: "S", sku: "LBS-WHT-S", stock: 19, cjVariantId: "CJV_LBS_WHT_S" },
      { id: "v003i", color: "Black", colorHex: "#1A1A1A", size: "S", sku: "LBS-BLK-S", stock: 11, cjVariantId: "CJV_LBS_BLK_S" },
      { id: "v003j", color: "Black", colorHex: "#1A1A1A", size: "M", sku: "LBS-BLK-M", stock: 13, cjVariantId: "CJV_LBS_BLK_M" },
    ],
    status: "Active",
    category: "Tops",
    tags: ["linen", "shirt", "oversized", "casual", "versatile"],
    rating: 4.6,
    reviewCount: 98,
    featured: true,
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "prod_004",
    name: "High-Waisted Tailored Trousers",
    slug: "high-waisted-tailored-trousers",
    description:
      "Cut with precision and designed to be worn constantly. Our tailored trousers feature a high-waist construction, side pockets, and a clean pressed front crease that give them a polished, elevated look. Made from our medium-weight fabric with just enough structure to hold their shape throughout the day. The slim-straight leg makes them easy to style with anything from a simple tee to a structured blazer.",
    shortDescription: "High-waist, slim-straight leg, front crease. The trouser for every occasion.",
    price: 74,
    compareAtPrice: 98,
    supplierCost: 20,
    shippingCost: 6.5,
    estimatedMargin: 47.5,
    images: [
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&auto=format&fit=crop&q=80",
    ],
    colors: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Charcoal", hex: "#2E2E2E" },
      { name: "Cream", hex: "#F2EDE4" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "68% Polyester, 28% Viscose, 4% Elastane — structured mid-weight blend",
    fit: "True to size. High-rise waist sits at natural waistline. Slim-straight leg. Model is 5'9\" wearing size S.",
    careInstructions: [
      "Dry clean recommended",
      "Or hand wash cold",
      "Do not bleach",
      "Hang to dry — do not tumble dry",
      "Press with cool iron on reverse",
    ],
    shippingInfo: "Free shipping on orders over $75. Standard delivery 7–14 business days.",
    returnInfo: "Free returns within 30 days of delivery. Items must be unworn, unwashed, and with original tags.",
    cjProductId: "CJ_TAILORED_004",
    variants: [
      { id: "v004a", color: "Camel", colorHex: "#C19A6B", size: "XS", sku: "HWT-CML-XS", stock: 14, cjVariantId: "CJV_HWT_CML_XS" },
      { id: "v004b", color: "Camel", colorHex: "#C19A6B", size: "S", sku: "HWT-CML-S", stock: 20, cjVariantId: "CJV_HWT_CML_S" },
      { id: "v004c", color: "Camel", colorHex: "#C19A6B", size: "M", sku: "HWT-CML-M", stock: 18, cjVariantId: "CJV_HWT_CML_M" },
      { id: "v004d", color: "Camel", colorHex: "#C19A6B", size: "L", sku: "HWT-CML-L", stock: 10, cjVariantId: "CJV_HWT_CML_L" },
      { id: "v004e", color: "Charcoal", colorHex: "#2E2E2E", size: "XS", sku: "HWT-CHR-XS", stock: 12, cjVariantId: "CJV_HWT_CHR_XS" },
      { id: "v004f", color: "Charcoal", colorHex: "#2E2E2E", size: "S", sku: "HWT-CHR-S", stock: 16, cjVariantId: "CJV_HWT_CHR_S" },
      { id: "v004g", color: "Charcoal", colorHex: "#2E2E2E", size: "M", sku: "HWT-CHR-M", stock: 14, cjVariantId: "CJV_HWT_CHR_M" },
      { id: "v004h", color: "Charcoal", colorHex: "#2E2E2E", size: "L", sku: "HWT-CHR-L", stock: 9, cjVariantId: "CJV_HWT_CHR_L" },
      { id: "v004i", color: "Cream", colorHex: "#F2EDE4", size: "S", sku: "HWT-CRM-S", stock: 11, cjVariantId: "CJV_HWT_CRM_S" },
      { id: "v004j", color: "Cream", colorHex: "#F2EDE4", size: "M", sku: "HWT-CRM-M", stock: 13, cjVariantId: "CJV_HWT_CRM_M" },
    ],
    status: "Active",
    category: "Bottoms",
    tags: ["tailored", "trousers", "high-waist", "work", "polished"],
    rating: 4.8,
    reviewCount: 163,
    featured: true,
    createdAt: "2026-02-05T10:00:00Z",
  },
];

export const getProductBySlug = (slug: string): Product | undefined =>
  PRODUCTS.find((p) => p.slug === slug);

export const getProductById = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);

export const getActiveProducts = (): Product[] =>
  PRODUCTS.filter((p) => p.status === "Active" || p.status === "Winner");

export const getFeaturedProducts = (): Product[] =>
  PRODUCTS.filter((p) => p.featured && (p.status === "Active" || p.status === "Winner"));
